### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by aaronspring** [observingClouds/xbitinfo#10]
Let’s try to keep our names a close to bitinformation.jl as possible. 

Rename
- https://github.com/observingClouds/bitinformation_pipeline/blob/master/bitinformation_pipeline/get_n_plot_bitinformation.jl to bitinformation.jl
- information_content or inflevels #9 
- please add here

**Comment by aaronspring** [comment]
to be more aligned to `bitinformation.jl`, I'd propose to rename `get_bitinformation` to `bitinformation` as in the original, `xr_bitround` to `round` (how to deal with `jl_bitround` then?)

**Comment by aaronspring** [comment]
Could also rename package to xbitinformation

**Comment by observingClouds** [comment]
For now I think we have implemented all changes suggested so far. I close it for now.
