### ISSUE TITLE
Add "Launch in AWS Studio Lab" to readme.md?

### ISSUE THREAD

**Issue by rsignell-usgs** [observingClouds/xbitinfo#104]
Not sure if you want to add this, but I've been loving AWS Studio Lab, and launching it worked perfectly -- it discovered the environment.yml, built the environment, I ran the notebook without problems.    And now the "bitinfo" env and repo are there for me to run again (on AWS Studio Lab, work is persisted, you can login with your account (free, no AWS account required) and you have 12 hours of CPU time every time you fire it up.  

Here's the proposed blurb for the readme:

## Launch in SageMaker Studio Lab
If you have an AWS SageMaker Studio Lab account, you can open in Studio Lab using the button below, then when prompted, choose to download the whole repo and to build the conda environment.   If you don't have an account, you can [sign up for free](https://studiolab.sagemaker.aws) (no AWS account required).

[![Open In SageMaker Studio Lab](https://studiolab.sagemaker.aws/studiolab.svg)](https://studiolab.sagemaker.aws/import/github/https://github.com/observingClouds/xbitinfo/blob/main/docs/quick-start.ipynb)

**Comment by aaronspring** [comment]
Whatever makes it easy to try is welcome
