### ISSUE TITLE
Saving to compressed zarr yields lower or negative compression

### ISSUE THREAD

**Issue by mattphysics** [observingClouds/xbitinfo#119]
* xbitinfo version:
xbitinfo                  0.0.2                    pypi_0    pypi

* Python version:
python                    3.10.5          hdaaf3db_0_cpython    conda-forge

* Operating System:
macOS Big Sur

### Description

I ran the tutorial notebook for saving to .nc and .zarr (https://xbitinfo.readthedocs.io/en/latest/quick-start.html). I expected progressively smaller file sizes, with "original" > "compressed" > "bitrounded". For .nc, this is what happened, while for .zarr 
1. the file size of the "original" is 30% smaller than for .nc (2.8 MB). 
2. Doing "ds.to_compressed_zarr") increases the size by 60% (4.5 MB). 
3. Saving the bitrounded data to compressed_zarr yields (as expected) a smaller file size (804 KB), which is 64% larger than the equivalent .nc file
![Screenshot 2022-07-14 at 20 46 55](https://user-images.githubusercontent.com/22072706/179214629-a016c42e-6693-4684-ab53-4c1f14f8fa72.png)
![Screenshot 2022-07-14 at 20 47 07](https://user-images.githubusercontent.com/22072706/179214663-04ec37bc-12b9-450c-9554-210846e45e39.png)

I have uploaded the notebook with results at https://github.com/mattphysics/xbitinfo/blob/main/tests/nb_xbitinfo_export.ipynb

**Comment by observingClouds** [comment]
Hi @mattphysics,
Thanks for trying out xbitinfo and opening this PR. The tricky part here is that `to_zarr` [compresses by default](            [assert actual.get_config() == blosc_comp.get_config()](https://github.com/pydata/xarray/blob/89b1fac6089aaf6f5cad58eda7f37c7db862a473/xarray/tests/test_backends.py#L2038)). This explains why the `xbitinfo/original.zarr` is much smaller than `xbitinfo/original.nc`. The `to_compressed_zarr` method that xbitinfo provides is rather optimised for bit rounded data and might have some overhead for a small file without bit rounding.

Check out https://github.com/observingClouds/xbitinfo/blob/4d5563e3416d61b26589abcdd32a08dd72fd361b/tests/test_save_compressed.py#L59-L71
Here we explicitly set the compression to `None` for the `to_zarr` method.

We should adapt this in the notebook as well.
