### ISSUE TITLE
bitrounding in python?

### ISSUE THREAD

**Issue by rsignell-usgs** [observingClouds/xbitinfo#125]
The bitrounding method calls Julia, but I just wanted to point out these routines in Python.

See appendix A4 here: https://gmd.copernicus.org/articles/14/377/2021/

**Comment by aaronspring** [comment]
We have the pythonic xr_bitround in xbitinfo/bitround.py:L69 and and julanic jl_bitround

**Comment by observingClouds** [comment]
I'm actually also working on a pythonic way to get the bitinformation, but it is still work in progress.

**Comment by rsignell-usgs** [comment]
@aaronspring, [indeed!](https://github.com/observingClouds/xbitinfo/blob/main/xbitinfo/bitround.py#L69-L101) .   I only noticed the julia one when skimming the code -- I will strive to more careful!
