### ISSUE TITLE
`eraint_uvz` `test_full` fails

### ISSUE THREAD

**Issue by aaronspring** [observingClouds/xbitinfo#139]
### Description

https://github.com/observingClouds/xbitinfo/actions/runs/3168552683/jobs/5159830575

```
assert compressed_size < ori_size
assert 9640058 < 4186398
```

Did defaults in `to_netcdf` change with new `xarray` release?

**Comment by observingClouds** [comment]
I checked the sizes for the different xarray releases:

`2022.06.0`:
```
ori_size = 4186398
compressed_size = 4131352
bitrounded_compressed_size = 496448
```

`2022.09.0`
```
ori_size = 4186398
compressed_size = 9640058
bitrounded_compressed_size = 447607
```

**Comment by observingClouds** [comment]
Okay, I think I know what is going on here. The behaviour of how the `encoding` argument in `to_netcdf` is interpreted has been changed from xarray `2022.06.0` to `2022.09.0`.

With `2022.09.0` xbitinfo overwrites the encoding when using `to_compressed_netcdf`. In this particular example, `z` has for example the original encoding of 
```python
{
    'source': '.../xarray_tutorial_data/e4bb6ebf67663eeab3ff30beae6a5acf-eraint_uvz.nc',
    'original_shape': (2, 3, 241, 480),
    'dtype': dtype('int16'),
    '_FillValue': nan,
    'scale_factor': -1.7250274674967954,
    'add_offset': 66825.5
}
```
The call of `get_compress_encoding_nc` within `to_compressed_netcdf` overwrites this encoding with
```python
{
    'zlib': True,
    'shuffle': True,
    'complevel': 9,
    'chunksizes': (2, 3, 241, 480)
}
```
In `2022.06.0` the encoding given to `to_netcdf` and the original encoding of a dataset were merged. As a consequence, values were written as compressed `int16` when calling `to_compressed_netcdf` while with the new version of xarray the compressed data is written as `float64`. The original dataset is written as `int16` in all cases.

**Comment by observingClouds** [comment]
Related upstream issue: https://github.com/pydata/xarray/issues/7127

**Comment by observingClouds** [comment]
And also related to https://github.com/pydata/xarray/issues/7129
