### ISSUE TITLE
register on pypi

### ISSUE THREAD

**Issue by aaronspring** [observingClouds/xbitinfo#14]
to allow `pip install bitinformation_pipeline`

**Comment by aaronspring** [comment]
waiting for https://github.com/zarr-developers/numcodecs/pull/299 to be merged
<img width="722" alt="Image Pasted at 2022-5-4 09-04" src="https://user-images.githubusercontent.com/12237157/166640583-6e66661e-c41f-4ca6-b9a0-194d3d0b6371.png">

**Comment by observingClouds** [comment]
https://github.com/zarr-developers/numcodecs/pull/299 is merged now 😄 However, I think the direct dependency issue from above remains until numcodecs is published in its newest version to pypi as well. Otherwise we still need to refer to the GitHub repository and get the error message above.

**Comment by observingClouds** [comment]
Upload to testpypi with modifications made in branch https://github.com/observingClouds/xbitinfo/tree/pypi still fails with the same error.

**Comment by rsignell-usgs** [comment]
@ocefpaf, can you help here?

**Comment by aaronspring** [comment]
I think we first need a numcodecs release or tag

**Comment by ocefpaf** [comment]
Yep. While there are a few updates I can send to the pypi.yaml GHA there is not much we can do here until the new numcodecs is released.

**Comment by observingClouds** [comment]
Yes, we currently depend on a new pypi release of numcodecs (https://github.com/zarr-developers/numcodecs/issues/324)

**Comment by observingClouds** [comment]
Version 0.10.0 has just been released! 🚀

**Comment by aaronspring** [comment]
probably #131 also helps with pypi

**Comment by observingClouds** [comment]
Closing as this is finally fixed by #132
