### ISSUE TITLE
make Julia optional dependency

### ISSUE THREAD

**Issue by aaronspring** [observingClouds/xbitinfo#151]
- used python implementation if Julia isn’t installed but throw warning
- use xr_bitround instead of jl_bitround

- helps #95 and Julia installation issues 
- Continues #126 
- In the pangeo show case @rsignell-usgs also copied some code to not import xbitinfo due to julia

**Comment by rsignell-usgs** [comment]
Just want to report here that the `xbitinfo-python` package worked nicely with the `quick-start.ipynb`: https://nbviewer.org/gist/7d297d9421f90bae38d69809f7028914

Great work guys!

**Comment by observingClouds** [comment]
Glad to hear that! We should adapt the README and mention the two different package versions there.
