### ISSUE TITLE
implement `xb.plot_bitinformation` for 16- and 64-bit inputs

### ISSUE THREAD

**Issue by aaronspring** [observingClouds/xbitinfo#168]
currently only plots correctly for 32bit, see #167

**Comment by aaronspring** [comment]
once implemented can remove `.astype(float32)` in quickstart

**Comment by aaronspring** [comment]
implementation idea:

![image](https://user-images.githubusercontent.com/12237157/203943807-0ec3eca5-eb8f-453b-a091-4c9daacb18c4.png)

**Comment by kar-hik** [comment]
Can you assign me this issue, I can work on this?

**Comment by kar-hik** [comment]
info_per_bit_cleaned = info_per_bit.where(info_per_bit > info_per.isel(bit64=slice(-4, None)).max() * 1.5)
info_per_bit_cleaned.to_array().plot(yincrease=False)
will this code work for bit64?

**Comment by aaronspring** [comment]
It should IMO but won't have the nicely formatted xticklabels, the step line for the 99% threshold etc

**Comment by kar-hik** [comment]
import matplotlib.pyplot as plt

# Set threshold at 1.5 times the max value of bit64
threshold = info_per_bit.isel(bit64=slice(-4, None)).max() * 1.5

# Select values above threshold
info_per_bit_cleaned = info_per_bit.where(info_per_bit > threshold)

# Plot data
fig, ax = plt.subplots()
info_per_bit_cleaned.plot(ax=ax, yincrease=False)

# Format xticklabels
ax.set_xticks(range(len(info_per_bit_cleaned.bit64)))
ax.set_xticklabels(info_per_bit_cleaned.bit64.values, rotation=90, fontsize=8)

# Add step line for 99% threshold
ax.axhline(threshold, linestyle='--', color='r', linewidth=1)

# Set axis labels and title
ax.set_xlabel('Bit position')
ax.set_ylabel('Information (bits)')
ax.set_title('Information content of bit positions in sequence')

plt.show()

hope atleast this works?

**Comment by aaronspring** [comment]
Please open a PR with that code and we will see in the rtd documentation of that branch the result

**Comment by aaronspring** [comment]
PR https://github.com/observingClouds/xbitinfo/pull/186

**Comment by observingClouds** [comment]
> I have created the PR with the code and i would like to give proposal for the GSoc 2023 so i wanted to know where can i submit the proposal sir?

@kar-hik you can submit the proposal [here](summerofcode.withgoogle.com/). Please be reminded about the different guidelines laid out on the [wiki page](https://github.com/observingClouds/xbitinfo/wiki/GSoC-Ideas#writing-the-proposal).
Application deadline is April 4th at 18 UTC!

**Comment by kar-hik** [comment]
[Link to drive ](https://drive.google.com/file/d/1GlH7DX-CFgT4C68BHotk60ba7oaDJqSY/view?usp=share_link) here with i am attaching my drive link of the proposal of the PDF since i was unable to upload the file in the given link kindly dont mistake me

> > I have created the PR with the code and i would like to give proposal for the GSoc 2023 so i wanted to know where can i submit the proposal sir?
> 
> @kar-hik you can submit the proposal [here](summerofcode.withgoogle.com/). Please be reminded about the different guidelines laid out on the [wiki page](https://github.com/observingClouds/xbitinfo/wiki/GSoC-Ideas#writing-the-proposal). Application deadline is April 4th at 18 UTC!

**Comment by observingClouds** [comment]
Hi @kar-hik,
sorry for the messed-up link. It is now corrected but because the deadline has passed this is of course not very helpful. The correct link was also posted on the wiki page though. I'm afraid it is too late for this year's GSoC, I cannot submit your proposal. I encourage you to apply next year again. If you are a citizen of Europe or currently work there, you might also want to look at the ECMWF Code4Earth challenges, in particular [challenge 13](https://github.com/ECMWFCode4Earth/challenges_2023/issues/3)

**Comment by observingClouds** [comment]
Hi @kar-hik,
Are you still interested in finishing up this issue and create a PR? I think you are quite close to the finish line!

**Comment by observingClouds** [comment]
This is now eventually fixed by #218
