### ISSUE TITLE
Move information content filtering from get_keepbits to get_bitinformation

### ISSUE THREAD

**Issue by observingClouds** [observingClouds/xbitinfo#17]
The filtering of the bit information is currently done in `get_keepbits`,  however, I think we should move this to `get_bitinformation` since this is the more appropriate place and we might even only return `ICfilt` in `get_bitinformation` because this is what people are most likely interested in.

This is the part I'm proposing to move to `get_bitinformation`:

```Julia
    # filter insignificant information via binomial distribution as explained in methods
    # for some variables the last bits do not have a free entropy of 1 bit, in that case
    # adjust the threshold by the information in the very last bits (which should always be 0)

    ic = values(bitinfo)
    p = BitInformation.binom_confidence(maskinfo,0.99)  # get chance p for 1 (or 0) from binom distr
    M₀ = 1 - entropy([p,1-p],2)                            # free entropy of random 50/50 at trial size
    threshold = max(M₀,1.5*maximum(ic[end-3:end]))         # in case the information never drops to zero
                                                               # use something a bit bigger than maximum
                                                               # of the last 4 bits
    insigni = (ic .<= threshold) .& (collect(1:length(ic)) .> 9)
    ic[insigni] .= floatmin(Float64)
```

**Comment by milankl** [comment]
Note that these lines
```julia
p = BitInformation.binom_confidence(maskinfo,0.99)  # get chance p for 1 (or 0) from binom distr
M₀ = 1 - entropy([p,1-p],2)                            # free entropy of random 50/50 at trial size
threshold = max(M₀,1.5*maximum(ic[end-3:end]))         # in case the information never drops to zero
                                                               # use something a bit bigger than maximum
                                                               # of the last 4 bits
insigni = (ic .<= threshold) .& (collect(1:length(ic)) .> 9)
ic[insigni] .= floatmin(Float64)
```
may have been still part of some analysis in Elefridge.jl, but they are now part of `bitinformation` and switched on(default)/off with the kwarg `set_zero_insignificant::Bool`. The `max(M₀,1.5*maximum(ic[end-3:end]))` was introduced whenever I dealt with datasets that contained some artificial information. At the moment I don't see a solid way to distinguish between real information and artificial real information without breaking the independency of bitpositions, which I honestly would love to keep. Hence I still suggest people to look at the bitinformation plots first (and share in BitInformation.jl iissues if unsure!). Suggestion: Let's keep the `max`-filtering out of the pipeline and if it remains a frequent issue then I'll think about how to include that (probably optionally) in BitInformation.jl?

**Comment by aaronspring** [comment]
So get_keepbits essentially boils down to argmax normed cdf. Could be also done easily in xarray.
