### ISSUE TITLE
Installing `xbitinfo` and running `xb.get_bitinformation` and `KeyError: 'dim'/`

### ISSUE THREAD

**Issue by ayoubft** [observingClouds/xbitinfo#187]
Hey, I am having a hard time getting started with `xbitinfo`

* xbitinfo version:  `0.0.4.dev1` through `conda-forge`
* Python version: `3.11.2`
* Operating System: `Manjaro Linux x86_64`

### Description

Trying to do the [getting started](https://xbitinfo.readthedocs.io/en/latest/quick-start.html) tutorial.
What is the best way to install it? especially for testing personal changes?

#### 1. `conda-forge`

* Created a conda env
* Installed `xbitinfo` through `conda-forge`
* None of the two variants of the `xb.get_bitinformations` would run (see output below).

#### 2. manual install of Julia + `pip install .` in the cloned github repo
Gives the same output as `1`

#### 3. manual install of Julia + `pip install .` + `pip install julia`

After running for a while, the import commands cause the Jupyter Notebook's kernel to suddenly disappear.

### Results

<details> <summary>Result of: <code>bitinfo = xb.get_bitinformation(ds, dim="lon", implementation="python") </code></summary>
<code>
Processing var: v for dim: lon: 100%|███████████████████████████████████| 3/3 [00:00<00:00, 51.30it/s]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~/.local/lib/python3.10/site-packages/xarray/core/dataset.py:1347, in Dataset._construct_dataarray(self, name)
   1346 try:
-> 1347     variable = self._variables[name]
   1348 except KeyError:
KeyError: 'dim'
During handling of the above exception, another exception occurred:
KeyError                                  Traceback (most recent call last)
Cell In[3], line 1
----> 1 bitinfo = xb.get_bitinformation(ds, dim="lon", implementation="python")  # calling bitinformation.jl.bitinformation
File ~/Projects/xbitinfo/xbitinfo/xbitinfo.py:249, in get_bitinformation(ds, dim, axis, label, overwrite, implementation, **kwargs)
    247             logging.debug(f"Save bitinformation to {label + '.json'}")
    248             json.dump(info_per_bit, f, cls=JsonCustomEncoder)
--> 249 info_per_bit = dict_to_dataset(info_per_bit)
    250 for var in info_per_bit.data_vars:  # keep attrs from input with source_ prefix
    251     for a in ds[var].attrs.keys():
File ~/Projects/xbitinfo/xbitinfo/xbitinfo.py:95, in dict_to_dataset(info_per_bit)
     91     if "bit" in c:
     92         dsb.coords[c].attrs = {
     93             "description": "name of the bits: '±' refers to the sign bit, 'e' to the exponents bits and 'm' to the mantissa bits."
     94         }
---> 95 dsb.coords["dim"].attrs = {
     96     "description": "dimension of the source dataset along which the bitwise information has been analysed."
     97 }
     98 return dsb
File ~/.local/lib/python3.10/site-packages/xarray/core/coordinates.py:290, in DatasetCoordinates.__getitem__(self, key)
    288 if key in self._data.data_vars:
    289     raise KeyError(key)
--> 290 return self._data[key]
File ~/.local/lib/python3.10/site-packages/xarray/core/dataset.py:1438, in Dataset.__getitem__(self, key)
   1436     return self.isel(**key)
   1437 if utils.hashable(key):
-> 1438     return self._construct_dataarray(key)
   1439 if utils.iterable_of_hashable(key):
   1440     return self._copy_listed(key)
File ~/.local/lib/python3.10/site-packages/xarray/core/dataset.py:1349, in Dataset._construct_dataarray(self, name)
   1347     variable = self._variables[name]
   1348 except KeyError:
-> 1349     _, name, variable = _get_virtual_variable(self._variables, name, self.dims)
   1351 needed_dims = set(variable.dims)
   1353 coords: dict[Hashable, Variable] = {}
File ~/.local/lib/python3.10/site-packages/xarray/core/dataset.py:185, in _get_virtual_variable(variables, key, dim_sizes)
    183 split_key = key.split(".", 1)
    184 if len(split_key) != 2:
--> 185     raise KeyError(key)
    187 ref_name, var_name = split_key
    188 ref_var = variables[ref_name]
KeyError: 'dim'/
</code>
</details>

<details> <summary>Result of: <code>bitinfo = xb.get_bitinformation(ds, dim="lon") </code></summary>
<code>
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[4], line 1
----> 1 bitinfo = xb.get_bitinformation(ds, dim="lon")  # calling bitinformation.jl.bitinformation
File ~/Projects/xbitinfo/xbitinfo/xbitinfo.py:179, in get_bitinformation(ds, dim, axis, label, overwrite, implementation, **kwargs)
    110 """Wrap `BitInformation.jl.bitinformation() <https://github.com/milankl/BitInformation.jl/blob/main/src/mutual_information.jl>`__.
    111 
    112 Parameters
   (...)
    176     BitInformation.jl_version:  ...
    177 """
    178 if implementation == "julia" and not julia_installed:
--> 179     raise ImportError('Please install julia or use implementation="python".')
    180 if dim is None and axis is None:
    181     # gather bitinformation on all axis
    182     return _get_bitinformation_along_dims(
    183         ds,
    184         dim=dim,
   (...)
    188         **kwargs,
    189     )
ImportError: Please install julia or use implementation="python".
</code>
</details>

**Comment by observingClouds** [comment]
Hi @ayoubft,
Thank you for reporting this issue. The 'how to use'-snippet did not have any dataset (`inpath` was not set). PR #192 will fix this now.

**Comment by observingClouds** [comment]
> What is the best way to install it? especially for testing personal changes?

The best way to install `xbitinfo` is via conda/mamba because those package managers make sure that all dependencies will be installed. If you then decide to test your own contributions, you need to clone this repository and install it with `pip -e` preferably in the same conda environment so that all dependencies are met. You can also follow the steps laid out in the [Contributor Guidelines](https://xbitinfo.readthedocs.io/en/latest/contributing.html#preparing-pull-requests).

**Comment by observingClouds** [comment]
The example in the README has now been updated. Feel free to reopen this issue if this does not solve your problem.
