### ISSUE TITLE
`RuntimeWarning: divide by zero encountered in log` in python implementation of `xb.get_bitinformation`

### ISSUE THREAD

**Issue by ayoubft** [observingClouds/xbitinfo#201]
Getting the bitinformation of a dataset using the `python` implementation, with the command:
```python
info_per_bit = xb.get_bitinformation(ds, dim="latitude", implementation="python")
```
is successful, but it generates a warning for each variable in the dataset:
```
/home/user/miniconda3/envs/bitinfo/lib/python3.11/site-packages/dask/core.py:119: 
RuntimeWarning: divide by zero encountered in log
  return func(*(_execute_task(a, cache) for a in args))
```
How to investigate the root cause of this?

**Comment by observingClouds** [comment]
Thanks for filing the issue @ayoubft!

My best idea right now would be to use `pdb` or `ipdb` and set a trace in the function you are calling with `import pdb; pdb.set_trace()` and then step through with `s` to see where the warning pops up.

**Comment by observingClouds** [comment]
Hi @ayoubft, you could try to go backwards and see which part in the `np.log` is causing a devision by zero. Is it `pr`, `ps` or both?
You might actually wanna try to replace `np.log(p / (pr * ps)))` with `np.ma.log(p / (pr * ps)))` because otherwise the mask of `p` is actually not applied.

Have a look at this simple example. One raises the warning, the other does not:
```python
import numpy as np
a = np.ma.array([0,1,2,3], mask=[True, False, False, False])

print(np.log(a))
#<ipython-input-9-89b6b8e53c58>:1: RuntimeWarning: divide by zero encountered in log
#  np.log(a)
#
#masked_array(data=[--, 0.0, 0.6931471805599453, 1.0986122886681098],
#             mask=[ True, False, False, False],
#       fill_value=1e+20)

print(np.ma.log(a))
# np.ma.log(a)
#
# masked_array(data=[--, 0.0, 0.6931471805599453, 1.0986122886681098],
#             mask=[ True, False, False, False],
#       fill_value=1e+20)
```
