### ISSUE TITLE
Apply signed_exponent only for floats and not for integers

### ISSUE THREAD

**Issue by observingClouds** [observingClouds/xbitinfo#206]
To make xbitinfo also work with integers, the signed_exponent function should only be applied in case the data variable contains a float datatype.

https://github.com/observingClouds/xbitinfo/blob/e133caaa067740998c2e784e759f17ae2611cc51/xbitinfo/xbitinfo.py#L296

based on discussion with @ayoubft, @milankl

**Comment by milankl** [comment]
Would adding a simple

**Comment by milankl** [comment]
I guess the default here is also that the `signed_exponent` isn't in-place by default to mess up your dataset in case it's not reversed to `biased_exponent`? But note that this will need to allocate the whole dataset twice!
