### ISSUE TITLE
Retrieval of maximum keepbits

### ISSUE THREAD

**Issue by observingClouds** [observingClouds/xbitinfo#22]
The bitwise information content can depend on the dimension `bitinformation` is applied to. Changes along dimensions like `lon` and `time` are rather small compared to those along the `lat` dimension. This might depend on the dataset though and the user might want to run the analysis across each dimension individually to identify the dimension with most keepbits and use those.

I propose to allow `get_bitinformation` handle a list of dims or a string like `maxdim` to return the keepbits of the dimension with the largest information content.

**Comment by aaronspring** [comment]
implementation idea: https://github.com/observingClouds/bitinformation_pipeline/pull/20/files#r843719538

**Comment by observingClouds** [comment]
> I would implement it at the beginning of `get_bitinformation`:
> 
> ```python
> def get_bitinformation(ds, dim):
>     if isinstance(dim, list):
>         for d in dim:
>             get_bitinformation(ds, d)
>         # somehow aggregate d results
> ```
> 

Copying comment of @aaronspring here for an easier discussion.

**Comment by aaronspring** [comment]
where do we implement this? could it be only done in `get_bitinformation` if so I'd propose `dim="max"`

`get_bitinformation` only gives us bitinformation and not directly `get_keepbits`.

**Comment by aaronspring** [comment]
as now `get_keepbits` is faster, we could internal run it inside `get_bitinformation` if `dim="max"` and then return the highest `get_keepbits` `info_per_bit` based on the standard `0.99` `inflevel`. Or we allow `inflevel` as another kwargs to be only used for that purpose

**Comment by aaronspring** [comment]
or maybe easier to implement: `def `get_max_keepbits(ds, inflevel)` with no dim or axis calling `get_bitinformation` in a loop over all dims and returning the highest.

**Comment by aaronspring** [comment]
or after #39, run `get_bitinformation(dim="max_or_all_or_None")` returns `info_per_bit` with dims `bit` and `dim`, then `get_keepbits` returns an `xr.Dataset(dim)` and the user can easily do `keepbits.max("dim")`

**Comment by observingClouds** [comment]
#88 is mostly in line with the last idea of yours:

1. `get_bitinformation` would retrieve by default the bitinformation along each dimension
2. the result of `get_bitinformation` is a `xr.Dataset` with dimensions `dim` and `bit<XY>`, where `<XY>` depends on the type of each variables e.g. `bit32` or `bit64`.
3. `get_keepbits` returns the keepbits along dimension `dim`
4. the user needs to do a `keepbits.max("dim")`
