### ISSUE TITLE
`KeyError: 'inflevel'` when using `xr.bitround`

### ISSUE THREAD

**Issue by ayoubft** [observingClouds/xbitinfo#226]
I am exploring chunking on some high-resolution dataset, and when I am bitrounding (`xr.bitround`) the sub-dataset using the calculated keepbits I get an : `KeyError: 'inflevel'`

Code:
```python
temp_ds = ds.isel(longitude=slice(0, 100), latitude=slice(0, 100))
temp_info_pbit = xb.get_bitinformation(temp_ds, dim=var, implementation="python")
temp_keepbits = xb.get_keepbits(temp_info_pbit, 0.99)
# cope with negative keepbits
temp_keepbits = temp_keepbits.map(at_least_zero)
temp_ds_bitrounded = xb.xr_bitround(temp_ds, temp_keepbits)
```
<details>
<summary>Full output</summary>
<pre>
KeyError                                  Traceback (most recent call last)
File ~/miniconda3/envs/bitinfo/lib/python3.11/site-packages/xarray/core/dataset.py:1382, in Dataset._construct_dataarray(self, name)
   1381 try:
-> 1382     variable = self._variables[name]
   1383 except KeyError:

KeyError: 'inflevel'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
Cell In[7], line 24
     22 temp_keepbits = temp_keepbits.map(at_least_zero)
     23 dss_kbits.append(temp_keepbits)
---> 24 temp_ds_bitrounded = xb.xr_bitround(temp_ds, temp_keepbits)
     25 dss_bitrounded.append(temp_ds_bitrounded)

File ~/xbitinfo/xbitinfo/bitround.py:93, in xr_bitround(da, keepbits)
     91     da_bitrounded = da.copy()
     92     for v in da.data_vars:
---> 93         da_bitrounded[v] = xr_bitround(da[v], keepbits)
     94     return da_bitrounded
     96 assert isinstance(da, xr.DataArray)

File ~/xbitinfo/xbitinfo/bitround.py:97, in xr_bitround(da, keepbits)
     94     return da_bitrounded
     96 assert isinstance(da, xr.DataArray)
---> 97 keep = _keepbits_interface(da, keepbits)
     99 da = xr.apply_ufunc(_np_bitround, da, keep, dask="parallelized", keep_attrs=True)
    100 da.attrs["_QuantizeBitRoundNumberOfSignificantDigits"] = keep

File ~/xbitinfo/xbitinfo/bitround.py:40, in _keepbits_interface(da, keepbits)
     38         raise ValueError(f"name {v} not for in keepbits: {keepbits.keys()}")
     39 elif isinstance(keepbits, xr.Dataset):
---> 40     assert keepbits.coords["inflevel"].shape <= (
     41         1,
     42     ), "Information content is only allowed for one 'inflevel' here. Please make a selection."
     43     if "dim" in keepbits.coords:
     44         assert keepbits.coords["dim"].shape <= (
     45             1,
     46         ), "Information content is only allowed along one dimension here. Please select one `dim`. To find the maximum keepbits, simply use `keepbits.max(dim='dim')`"

File ~/miniconda3/envs/bitinfo/lib/python3.11/site-packages/xarray/core/coordinates.py:290, in DatasetCoordinates.__getitem__(self, key)
    288 if key in self._data.data_vars:
    289     raise KeyError(key)
--> 290 return self._data[key]

File ~/miniconda3/envs/bitinfo/lib/python3.11/site-packages/xarray/core/dataset.py:1473, in Dataset.__getitem__(self, key)
   1471     return self.isel(**key)
   1472 if utils.hashable(key):
-> 1473     return self._construct_dataarray(key)
   1474 if utils.iterable_of_hashable(key):
   1475     return self._copy_listed(key)

File ~/miniconda3/envs/bitinfo/lib/python3.11/site-packages/xarray/core/dataset.py:1384, in Dataset._construct_dataarray(self, name)
   1382     variable = self._variables[name]
   1383 except KeyError:
-> 1384     _, name, variable = _get_virtual_variable(self._variables, name, self.dims)
   1386 needed_dims = set(variable.dims)
   1388 coords: dict[Hashable, Variable] = {}

File ~/miniconda3/envs/bitinfo/lib/python3.11/site-packages/xarray/core/dataset.py:196, in _get_virtual_variable(variables, key, dim_sizes)
    194 split_key = key.split(".", 1)
    195 if len(split_key) != 2:
--> 196     raise KeyError(key)
    198 ref_name, var_name = split_key
    199 ref_var = variables[ref_name]

KeyError: 'inflevel'</pre>

**Comment by observingClouds** [comment]
Hi @ayoubft,
Could you let me know which xbitinfo version you are using, e.g. print the output of `xb.__version__`. I cannot see a reason why this should work with a small dataset but not with a larger one.

**Comment by ayoubft** [comment]
Hey @observingClouds, it is version `'0.0.4.dev157+g3ea856f'`.

**Comment by ayoubft** [comment]
I have found the bug, it is from my side:

* I am using this function `at_least_zero` to discard negative keeepbits (that are still not supported?) to zero
  * but it makes the `keepbits` dataset with empty dimensions and variables (see image below)

I am working on addressing it ...

![image](https://github.com/observingClouds/xbitinfo/assets/63267601/41f2eb31-0ee2-4dc4-8e8c-717c1ccc3c59)

**Comment by ayoubft** [comment]
I circumvented this by changing only the data of the `temp_keepbits` dataset:

```python
var_kp = list(temp_keepbits.keys())[0]
# cope with negative keepbits
temp_keepbits[var_kp].data = at_least_zero(temp_keepbits[var_kp].data)
```

**Comment by observingClouds** [comment]
How did you define `at_least_zero`? Can't you use an xarray function for this, so you keep an xarray Dataset object? E.g. `temp_keepbits.where(temp_keepbits >=0, drop=True)`?

**Comment by ayoubft** [comment]
This is the function: `at_least_zero = lambda x: max(x, 0)`. 

So originally I was using the `map` function but failed to keep the keepbit dataset as the original, also this keepbits dataset has only one value so I think the `where` won't work for changing the negative value to zero.

This gets us back to the need for supporting negative keepbits.

**Comment by observingClouds** [comment]
Great! If this is fixed, please close the issue. Feel free to suggest improvements of the documentation.
