### ISSUE TITLE
Separation of dependencies

### ISSUE THREAD

**Issue by observingClouds** [observingClouds/xbitinfo#267]
Dependencies of tests, documentation, setup and usage got a bit mixed up over time. It would be good to separate the dependencies again.

- https://github.com/observingClouds/xbitinfo/blob/main/docs/environment.yml
- https://github.com/observingClouds/xbitinfo/blob/main/environment.yml
- https://github.com/observingClouds/xbitinfo/blob/main/requirements.txt
- https://github.com/observingClouds/xbitinfo/blob/main/setup.py

**Comment by shivamagar** [comment]
I love to work on this ..

**Comment by observingClouds** [comment]
Please go ahead @shivamagar! I assign this issue to you.

**Comment by observingClouds** [comment]
@shivamagar how are you progressing? If you are no longer interested in solving this issue or are too busy, please let us know. If I do not hear back from you within a week I will automatically unassigned you to give others an opportunity to tackle this issue.

**Comment by AryanBakliwal** [comment]
Hi @observingClouds, I would like to work on this issue please assign me
