### ISSUE TITLE
Feat: Use `ruff` as linting tool and remove `flake8`

### ISSUE THREAD

**Issue by fnhirwa** [observingClouds/xbitinfo#270]
* xbitinfo version:
* Python version:
* Operating System:

### Description

`ruff` is fastest linter and code formatter written in rust.
https://github.com/astral-sh/ruff

**Comment by observingClouds** [comment]
Cool! 😎 Do you like to do a PR?

**Comment by fnhirwa** [comment]
> Cool! 😎 Do you like to do a PR?
Yeah I can start working on the PR 🤞
