### ISSUE TITLE
[Docs] Fix Documentations rendering issues

### ISSUE THREAD

**Issue by fnhirwa** [observingClouds/xbitinfo#279]
### Description

Here is an example where examples were rendered incorrectly. The task should be inspecting the docs and applying fixes accordingly.
![image](https://github.com/observingClouds/xbitinfo/assets/67042527/845c555b-56e1-4fea-a420-e245313fc496)
[Link](https://xbitinfo.readthedocs.io/en/latest/api/xbitinfo.xbitinfo.get_prefect_flow.html#xbitinfo.xbitinfo.get_prefect_flow)

**Comment by observingClouds** [comment]
Good catch @fnhirwa. Feel free to open a PR.
